---
name: CI/CD
on:
  push:
    - master
    - 'WIP**'
    - '4.*'
  pull_request:
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    container: ultimaker/cura-build-environment
    steps:
    - name: Checkout Cura
      uses: actions/checkout@v2
    - name: Build and test
      run: docker/build.sh
