---
name: CI/CD
on:
  push:
    branches:
      - master
      - 'WIP**'
      - '4.*'
      - 'CURA-*'
  pull_request:
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    container: ultimaker/cura-build-environment
    steps:
    - name: Checkout Cura
      uses: actions/checkout@v2
    - name: Build and test
      run: docker/build.sh
    - name: Check dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install safety
        safety check
