name: Create and Upload Conan package

on:
    workflow_call:
        inputs:
            project_name:
                required: true
                type: string

            recipe_id_full:
                required: true
                type: string

            recipe_id_latest:
                required: false
                type: string

            runs_on:
                required: true
                type: string

            python_version:
                required: true
                type: string

            conan_config_branch:
                required: false
                type: string

            conan_logging_level:
                required: false
                type: string

            conan_clean_local_cache:
                required: false
                type: boolean
                default: false

            conan_upload_community:
                required: false
                default: true
                type: boolean

            create_from_source:
                required: false
                default: false
                type: boolean

env:
    CONAN_LOGIN_USERNAME_CURA: ${{ secrets.CONAN_USER }}
    CONAN_PASSWORD_CURA: ${{ secrets.CONAN_PASS }}
    CONAN_LOGIN_USERNAME_CURA_CE: ${{ secrets.CONAN_USER }}
    CONAN_PASSWORD_CURA_CE: ${{ secrets.CONAN_PASS }}
    CONAN_LOG_RUN_TO_OUTPUT: 1
    CONAN_LOGGING_LEVEL: ${{ inputs.conan_logging_level }}
    CONAN_NON_INTERACTIVE: 1

jobs:
    conan-package-create:
        runs-on: ${{ inputs.runs_on }}

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Setup Python and pip
                uses: actions/setup-python@v4
                with:
                    python-version: ${{ inputs.python_version }}
                    cache: 'pip'
                    cache-dependency-path: .github/workflows/requirements-conan-package.txt

            -   name: Install Python requirements for runner
                run: pip install -r .github/workflows/requirements-conan-package.txt

            -   name: Use Conan download cache (Bash)
                if: ${{ runner.os != 'Windows' }}
                run: conan config set storage.download_cache="$HOME/.conan/conan_download_cache"

            -   name: Use Conan download cache (Powershell)
                if: ${{ runner.os == 'Windows' }}
                run: conan config set storage.download_cache="C:\Users\runneradmin\.conan\conan_download_cache"

            -   name: Cache Conan local repository packages (Bash)
                uses: actions/cache@v3
                if: ${{ runner.os != 'Windows' }}
                with:
                    path: |
                        $HOME/.conan/data
                        $HOME/.conan/conan_download_cache
                    key: conan-${{ runner.os }}-${{ runner.arch }}-create-cache

            -   name: Cache Conan local repository packages (Powershell)
                uses: actions/cache@v3
                if: ${{ runner.os == 'Windows' }}
                with:
                    path: |
                        C:\Users\runneradmin\.conan\data
                        C:\.conan
                        C:\Users\runneradmin\.conan\conan_download_cache
                    key: conan-${{ runner.os }}-${{ runner.arch }}-create-cache

            -   name: Install MacOS system requirements
                if:  ${{ runner.os == 'Macos' }}
                run: brew install autoconf automake ninja

            -   name: Install Linux system requirements
                if: ${{ runner.os == 'Linux' }}
                run: |
                    sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
                    sudo apt update
                    sudo apt upgrade
                    sudo apt install build-essential checkinstall libegl-dev zlib1g-dev libssl-dev ninja-build autoconf libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev libxaw7-dev libxcomposite-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev libxfixes-dev libxi-dev libxinerama-dev libxkbfile-dev libxmu-dev libxmuu-dev libxpm-dev libxrandr-dev libxrender-dev libxres-dev libxss-dev libxt-dev libxtst-dev libxv-dev libxvmc-dev libxxf86vm-dev xtrans-dev libxcb-render0-dev libxcb-render-util0-dev libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb-xinerama0-dev xkb-data libxcb-dri3-dev uuid-dev libxcb-util-dev libxkbcommon-x11-dev pkg-config -y

            -   name: Install GCC-12 on ubuntu-22.04
                if: ${{ startsWith(inputs.runs_on, 'ubuntu-22.04') }}
                run: |
                    sudo apt install g++-12 gcc-12 -y
                    sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 12
                    sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 12

            -   name: Create the default Conan profile
                run:  conan profile new default --detect

            -   name: Get Conan configuration from branch
                if: ${{ inputs.conan_config_branch != '' }}
                run: conan config install https://github.com/Ultimaker/conan-config.git -a "-b ${{ inputs.conan_config_branch }}"

            -   name: Get Conan configuration
                if: ${{ inputs.conan_config_branch == '' }}
                run: conan config install https://github.com/Ultimaker/conan-config.git

            -  name: Associate build information with the Conan package
               run: conan_build_info --v2 start ${{ inputs.project_name }} ${{ github.run_number }}

            -   name: Create the Packages
                if: ${{ !inputs.create_from_source }}
                run: conan install ${{ inputs.recipe_id_full }} --build=missing --update

            -   name: Create the Packages (from source)
                if: ${{ inputs.create_from_source }}
                run: conan create . ${{ inputs.recipe_id_full }} --build=missing --update

            -   name: Remove the latest alias
                if: ${{ inputs.create_from_source && inputs.recipe_id_latest != '' && runner.os == 'Linux' }}
                run: |
                    conan remove ${{ inputs.recipe_id_latest }} -r cura -f || true
                    conan remove ${{ inputs.recipe_id_latest }} -r cura-ce -f || true

            -   name: Create the latest alias
                if: ${{ inputs.create_from_source && inputs.recipe_id_latest != '' && always() }}
                run: conan alias ${{ inputs.recipe_id_latest }} ${{ inputs.recipe_id_full }}

            -   name: Upload the Package(s)
                if: always()
                run: conan upload "*" -r cura --all -c

            -   name: Upload the Package(s) community
                if: ${{ always() && inputs.conan_upload_community == true }}
                run: conan upload "*" -r cura-ce -c

            -  name: Create and Upload the build info
               run: |
                   conan_build_info --v2 create buildinfo.json --lockfile conan.lock --user ${{ secrets.CONAN_USER }} --password ${{ secrets.CONAN_PASS }}
                   conan_build_info --v2 publish buildinfo.json --url https://ultimaker.jfrog.io/artifactory --user ${{ secrets.CONAN_USER }} --password ${{ secrets.CONAN_PASS }}
