name: conan-package-resources

on:
  push:
    paths:
      - '.github/workflows/conan-package-resources.yml'
      - 'resources/definitions/**'
      - 'resources/extruders/**'
      - 'resources/images/**'
      - 'resources/intent/**'
      - 'resources/meshes/**'
      - 'resources/quality/**'
      - 'resources/variants/**'
      - 'resources/conanfile.py'
    branches:
      - 'main'
      - 'CURA-*'
      - 'PP-*'
      - 'NP-*'
      - '[0-9].[0-9]*'
      - '[0-9].[0-9][0-9]*'

jobs:
# FIXME: Use main once merged
  conan-package:
    uses: ultimaker/cura-workflows/.github/workflows/conan-package.yml@CURA-11622_conan_v2
    with:
      project_name: cura_resources
      conan_recipe_root: "./resources/"
      platform_windows: false
      platform_mac: false
    secrets: inherit
