name: Linux Installer
run-name: ${{ inputs.cura_conan_version }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      cura_conan_version:
        description: 'Cura Conan Version'
        default: 'cura/latest@ultimaker/testing'
        required: true
        type: string
      conan_args:
        description: 'Conan args, e.g. --requires'
        default: ''
        required: false
        type: string
      enterprise:
        description: 'Build Cura as an Enterprise edition'
        default: false
        required: true
        type: boolean
      staging:
        description: 'Use staging API'
        default: false
        required: true
        type: boolean
      operating_system:
        description: 'OS'
        required: true
        default: 'self-hosted-Ubuntu22-X64'
        type: choice
        options:
          - ubuntu-22.04
          - self-hosted-Ubuntu22-X64

jobs:
# FIXME: Use main once merged
  linux-installer:
    uses: ultimaker/cura-workflows/.github/workflows/cura-installer-linux.yml@CURA-11622_conan_v2
    with:
      cura_conan_version: ${{ inputs.cura_conan_version }}
      conan_args: ${{ inputs.conan_args }}
      enterprise: ${{ inputs.enterprise }}
      staging: ${{ inputs.staging }}
      operating_system: ${{ inputs.operating_system }}
    secrets: inherit
